const kanjiData = {
    N5: [
        { kanji: "一", meaning: ["one", "1"] },
        { kanji: "二", meaning: ["two", "2"] },
        { kanji: "三", meaning: ["three", "3"] },
        { kanji: "四", meaning: ["four", "4"] },
        { kanji: "五", meaning: ["five", "5"] },
        { kanji: "六", meaning: ["six", "6"] },
        { kanji: "七", meaning: ["seven", "7"] },
        { kanji: "八", meaning: ["eight", "8"] },
        { kanji: "九", meaning: ["nine", "9"] },
        { kanji: "十", meaning: ["ten", "10"] },
        { kanji: "百", meaning: ["hundred", "100"] },
        { kanji: "千", meaning: ["thousand", "1000"] },
        { kanji: "万", meaning: ["ten thousand", "10000"] },
        { kanji: "円", meaning: ["yen", "circle"] },
        { kanji: "日", meaning: ["day", "sun", "Japan"] },
        { kanji: "月", meaning: ["month", "moon"] },
        { kanji: "火", meaning: ["fire"] },
        { kanji: "水", meaning: ["water"] },
        { kanji: "木", meaning: ["tree", "wood"] },
        { kanji: "金", meaning: ["gold", "money", "Friday"] },
        { kanji: "土", meaning: ["soil", "earth", "Saturday"] },
        { kanji: "曜", meaning: ["weekday"] },
        { kanji: "年", meaning: ["year"] },
        { kanji: "時", meaning: ["time", "hour"] },
        { kanji: "間", meaning: ["interval", "between"] },
        { kanji: "分", meaning: ["minute", "part", "understand"] },
        { kanji: "秒", meaning: ["second"] },
        { kanji: "上", meaning: ["above", "up"] },
        { kanji: "下", meaning: ["below", "down"] },
        { kanji: "左", meaning: ["left"] },
        { kanji: "右", meaning: ["right"] },
        { kanji: "中", meaning: ["middle", "inside"] },
        { kanji: "大", meaning: ["big", "large"] },
        { kanji: "小", meaning: ["small", "little"] },
        { kanji: "人", meaning: ["person"] },
        { kanji: "男", meaning: ["man", "male"] },
        { kanji: "女", meaning: ["woman", "female"] },
        { kanji: "子", meaning: ["child"] },
        { kanji: "父", meaning: ["father"] },
        { kanji: "母", meaning: ["mother"] },
        { kanji: "友", meaning: ["friend"] },
        { kanji: "学", meaning: ["study", "learning"] },
        { kanji: "生", meaning: ["life", "birth"] },
        { kanji: "先", meaning: ["previous", "ahead"] },
        { kanji: "校", meaning: ["school"] },
        { kanji: "本", meaning: ["book", "origin"] },
        { kanji: "山", meaning: ["mountain"] },
        { kanji: "川", meaning: ["river"] },
        { kanji: "田", meaning: ["rice field"] },
        { kanji: "天", meaning: ["heaven", "sky"] },
        { kanji: "雨", meaning: ["rain"] },
        { kanji: "電", meaning: ["electricity"] },
        { kanji: "気", meaning: ["spirit", "energy"] },
        { kanji: "車", meaning: ["car", "vehicle"] },
        { kanji: "語", meaning: ["language", "word"] },
        { kanji: "国", meaning: ["country"] },
        { kanji: "名", meaning: ["name"] },
        { kanji: "店", meaning: ["shop", "store"] },
        { kanji: "社", meaning: ["company", "shrine"] },
        { kanji: "駅", meaning: ["station"] },
        { kanji: "道", meaning: ["road", "way"] },
        { kanji: "東", meaning: ["east"] },
        { kanji: "西", meaning: ["west"] },
        { kanji: "南", meaning: ["south"] },
        { kanji: "北", meaning: ["north"] },
        { kanji: "口", meaning: ["mouth", "opening"] },
        { kanji: "目", meaning: ["eye"] },
        { kanji: "耳", meaning: ["ear"] },
        { kanji: "手", meaning: ["hand"] },
        { kanji: "足", meaning: ["foot", "leg"] },
        { kanji: "力", meaning: ["power", "strength"] },
        { kanji: "食", meaning: ["eat", "food"] },
        { kanji: "飲", meaning: ["drink"] },
        { kanji: "行", meaning: ["go", "conduct"] },
        { kanji: "来", meaning: ["come"] },
        { kanji: "見", meaning: ["see", "look"] },
        { kanji: "聞", meaning: ["hear", "ask"] },
        { kanji: "書", meaning: ["write"] },
        { kanji: "読", meaning: ["read"] },
        { kanji: "話", meaning: ["talk", "speak"] }
    ],
    
    N4: [
        { kanji: "会", meaning: ["meeting", "meet"] },
        { kanji: "同", meaning: ["same"] },
        { kanji: "事", meaning: ["thing", "matter"] },
        { kanji: "自", meaning: ["self"] },
        { kanji: "知", meaning: ["know"] },
        { kanji: "理", meaning: ["reason", "logic"] },
        { kanji: "発", meaning: ["departure", "discharge"] },
        { kanji: "明", meaning: ["bright", "clear"] },
        { kanji: "員", meaning: ["member"] },
        { kanji: "堂", meaning: ["hall", "public chamber"] },
        { kanji: "病", meaning: ["illness"] },
        { kanji: "院", meaning: ["institution"] },
        { kanji: "品", meaning: ["goods", "article"] },
        { kanji: "安", meaning: ["cheap", "peaceful"] },
        { kanji: "高", meaning: ["high", "expensive"] },
        { kanji: "新", meaning: ["new"] },
        { kanji: "古", meaning: ["old"] },
        { kanji: "長", meaning: ["long", "leader"] },
        { kanji: "多", meaning: ["many", "much"] },
        { kanji: "少", meaning: ["few", "little"] },
        { kanji: "広", meaning: ["wide", "broad"] },
        { kanji: "強", meaning: ["strong"] },
        { kanji: "弱", meaning: ["weak"] },
        { kanji: "早", meaning: ["early", "fast"] },
        { kanji: "昼", meaning: ["noon", "daytime"] },
        { kanji: "夜", meaning: ["night"] },
        { kanji: "朝", meaning: ["morning"] },
        { kanji: "春", meaning: ["spring"] },
        { kanji: "夏", meaning: ["summer"] },
        { kanji: "秋", meaning: ["autumn"] },
        { kanji: "冬", meaning: ["winter"] },
        { kanji: "毎", meaning: ["every"] },
        { kanji: "今", meaning: ["now"] },
        { kanji: "前", meaning: ["before", "front"] },
        { kanji: "後", meaning: ["after", "behind"] },
        { kanji: "外", meaning: ["outside"] },
        { kanji: "名", meaning: ["name", "famous"] },
        { kanji: "県", meaning: ["prefecture"] },
        { kanji: "市", meaning: ["city"] },
        { kanji: "町", meaning: ["town"] },
        { kanji: "村", meaning: ["village"] },
        { kanji: "番", meaning: ["number", "turn"] },
        { kanji: "号", meaning: ["number", "issue"] },
        { kanji: "風", meaning: ["wind", "style"] },
        { kanji: "雪", meaning: ["snow"] },
        { kanji: "雲", meaning: ["cloud"] },
        { kanji: "星", meaning: ["star"] },
        { kanji: "海", meaning: ["sea", "ocean"] },
        { kanji: "池", meaning: ["pond"] },
        { kanji: "林", meaning: ["woods", "forest"] },
        { kanji: "森", meaning: ["forest"] },
        { kanji: "原", meaning: ["field", "plain"] },
        { kanji: "花", meaning: ["flower"] },
        { kanji: "草", meaning: ["grass"] },
        { kanji: "竹", meaning: ["bamboo"] },
        { kanji: "茶", meaning: ["tea"] },
        { kanji: "肉", meaning: ["meat"] },
        { kanji: "魚", meaning: ["fish"] },
        { kanji: "牛", meaning: ["cow"] },
        { kanji: "馬", meaning: ["horse"] },
        { kanji: "鳥", meaning: ["bird"] },
        { kanji: "犬", meaning: ["dog"] },
        { kanji: "猫", meaning: ["cat"] },
        { kanji: "虫", meaning: ["insect"] },
        { kanji: "体", meaning: ["body"] },
        { kanji: "頭", meaning: ["head"] },
        { kanji: "顔", meaning: ["face"] },
        { kanji: "心", meaning: ["heart", "mind"] },
        { kanji: "考", meaning: ["think", "consider"] },
        { kanji: "思", meaning: ["think"] },
        { kanji: "言", meaning: ["say", "word"] },
        { kanji: "答", meaning: ["answer"] },
        { kanji: "教", meaning: ["teach", "religion"] },
        { kanji: "習", meaning: ["learn"] },
        { kanji: "主", meaning: ["main", "master"] },
        { kanji: "世", meaning: ["world", "generation"] },
        { kanji: "界", meaning: ["world"] },
        { kanji: "住", meaning: ["dwell", "live"] },
        { kanji: "活", meaning: ["active", "life"] },
        { kanji: "仕", meaning: ["serve", "work"] },
        { kanji: "業", meaning: ["business", "work"] },
        { kanji: "仕事", meaning: ["job", "work"] },
        { kanji: "医者", meaning: ["doctor"] },
        { kanji: "研究者", meaning: ["researcher"] }
    ]
};